/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#3f465c",
        "on-surface-variant": "#45464d",
        "outline-variant": "#c6c6cd",
        "secondary-fixed": "#ffddb8",
        "on-primary": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "on-secondary": "#ffffff",
        "on-primary-container": "#7c839b",
        "on-primary-fixed": "#131b2e",
        "on-tertiary-container": "#75859d",
        "on-surface": "#191c1e",
        "on-secondary-fixed": "#2a1700",
        "tertiary-container": "#0b1c30",
        "tertiary-fixed-dim": "#b7c8e1",
        "inverse-primary": "#bec6e0",
        "secondary-fixed-dim": "#ffb95f",
        "accent-warm": "#F59E0B",
        "background": "#f7f9fb",
        "tertiary-fixed": "#d3e4fe",
        "secondary-container": "#fea619",
        "on-tertiary-fixed": "#0b1c30",
        "text-muted": "#475569",
        "surface-container-highest": "#e0e3e5",
        "surface-container": "#eceef0",
        "tertiary": "#000000",
        "on-background": "#191c1e",
        "on-secondary-container": "#684000",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#38485d",
        "inverse-on-surface": "#eff1f3",
        "inverse-surface": "#2d3133",
        "error": "#ba1a1a",
        "surface-container-high": "#e6e8ea",
        "surface-bright": "#f7f9fb",
        "surface-tint": "#565e74",
        "primary-fixed": "#dae2fd",
        "text-main": "#0F172A",
        "secondary": "#855300",
        "on-secondary-fixed-variant": "#653e00",
        "outline": "#76777d",
        "on-error-container": "#93000a",
        "surface-variant": "#e0e3e5",
        "primary-container": "#131b2e",
        "primary-fixed-dim": "#bec6e0",
        "primary": "#000000",
        "on-error": "#ffffff",
        "surface": "#FFFFFF",
        "background-alt": "#F1F5F9",
        "surface-dim": "#d8dadc",
        "surface-container-lowest": "#ffffff"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        "xl": "0.75rem",
        full: "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "margin-mobile": "1rem",
        "stack-lg": "2rem",
        "section-gap-desktop": "8rem",
        "stack-md": "1rem",
        "section-gap-mobile": "4rem",
        "gutter": "1.5rem",
        "stack-sm": "0.5rem"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
};
